"""Render a shaded 3D surface from a saved, normalized FDK walnut volume.

Run using the CUDA PyTorch environment:
  python docs/video/make_walnut_3d.py path/to/walnut128.npy
The volume is generated by upstream 2.0.2 walnut_reconstruction.py --size 128
--algorithms --save-volume walnut128.npy. This is a thresholded CT surface,
not a photograph. No generative imagery or synthetic walnut geometry is used.
"""
import argparse
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('volume', type=Path)
    parser.add_argument('--frames', type=int, default=180)
    parser.add_argument('--resolution', type=int, default=512)
    args = parser.parse_args()
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    raw = np.flip(np.load(args.volume), axis=0).copy().astype(np.float32)
    volume = torch.from_numpy(raw)[None, None].to(device)
    # Mild smoothing removes voxel stair steps before extracting a 0.30 isosurface.
    weights = torch.tensor([1., 2., 1.], device=device) / 4
    for dim in range(3):
        shape = [1, 1, 1, 1, 1]; shape[dim + 2] = 3
        padding = [0, 0, 0]; padding[dim] = 1
        volume = F.conv3d(volume, weights.reshape(shape), padding=padding)
    gradients = torch.gradient(volume[0, 0], dim=(0, 1, 2))
    normals = torch.stack([gradients[2], gradients[1], gradients[0]])[None]
    n = args.resolution
    extent, elevation = 1.35, np.deg2rad(22)
    coords = torch.linspace(-extent, extent, n, device=device)
    vv, uu = torch.meshgrid(coords.flip(0), coords, indexing='ij')
    depths = torch.linspace(1.75, -1.75, 192, device=device)
    light = torch.tensor([-0.45, 0.65, 0.8], device=device)
    light /= light.norm()
    images = []
    for index in range(args.frames):
        azimuth = np.deg2rad(-35 + 360 * index / args.frames)
        ex = torch.tensor([np.cos(azimuth), -np.sin(azimuth), 0], dtype=torch.float32, device=device)
        ey = torch.tensor([np.sin(elevation)*np.sin(azimuth), np.sin(elevation)*np.cos(azimuth), np.cos(elevation)], dtype=torch.float32, device=device)
        ez = torch.linalg.cross(ex, ey)
        plane = uu[...,None]*ex + vv[...,None]*ey
        grid = plane[None] + depths[:,None,None,None]*ez
        samples = F.grid_sample(volume, grid[None], align_corners=True)[0,0]
        hit = samples >= .30
        valid = hit.any(dim=0)
        first = hit.to(torch.int32).argmax(dim=0)
        # Interpolate the threshold crossing between ray samples for smooth silhouettes.
        before = (first-1).clamp_min(0)
        front = samples.gather(0,before[None])[0]
        back = samples.gather(0,first[None])[0]
        fraction = ((.30-front)/(back-front).clamp_min(1e-6)).clamp(0,1)
        depth = depths[before] + fraction*(depths[first]-depths[before])
        surface = plane + depth[...,None]*ez
        normal = -F.grid_sample(normals,surface[None,None],align_corners=True)[0,:,0].permute(1,2,0)
        normal = F.normalize(normal,dim=-1)
        screen_normal = torch.stack([normal@ex,normal@ey,normal@ez],dim=-1)
        lambert = (screen_normal@light).clamp(0,1)
        brightness = .34 + .66*lambert
        rgb = brightness[...,None] * torch.tensor([183.,164.,137.],device=device)
        alpha = valid.to(torch.float32)[...,None]*255
        rgba = torch.cat([rgb,alpha],dim=-1).clamp(0,255).to(torch.uint8).cpu().numpy()
        images.append(rgba)
        if index == 0:
            first_depth = torch.where(valid, depth, -torch.inf).cpu().numpy()
        if index % 20 == 0: print(f'surface {index}/{args.frames}',flush=True)
    target=Path(__file__).with_name('walnut_surface.npz')
    np.savez_compressed(target, frames=np.stack(images), depth=first_depth, azimuth_start=-35., elevation=22., extent=extent,
                        threshold=.30, volume_shape=raw.shape)
    print(target)


if __name__ == '__main__':
    main()
